<Project>
    <ItemGroup>
        <Compile Include="src/**/*.cs" Condition="'$(ValidateMerged)' == ''" />
        <Compile Include="$(ValidateMerged)" Condition="'$(ValidateMerged)' != ''" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SkipPostBuild)' != 'true'">
        <!-- Merge files in src into a single plugin file that can be installed on game servers -->
        <Exec Command="dotnet tool run plugin.merge -- -m -c -p merge.json" />

        <!-- Merge partial classes if NodeJS is available (requires `npm install`). If Plugin.Merge eventually supports merging partial classes natively, this can be removed. -->
        <Exec
            Command="where npx"
            IgnoreExitCode="true"
            StandardOutputImportance="low"
            StandardErrorImportance="low"
            Condition="Exists('node_modules')"
        >
            <Output TaskParameter="ExitCode" PropertyName="NpxExitCode" />
        </Exec>
        <Exec
            Command="npx tsx scripts/post-merge.ts MyCarbonoxide.cs"
            Condition="'$(NpxExitCode)' == '0' And '$(LiteEdition)' != 'true'"
        />

        <!-- Lite edition -->
        <Error
            Condition="'$(LiteEdition)' == 'true' And '$(NpxExitCode)' != '0'"
            Text="LiteEdition needs NodeJS to build. Install NodeJS and run `npm install`."
        />
        <Copy
            SourceFiles="MyCarbonoxide.cs"
            DestinationFiles="lite/MyCarbonoxide.cs"
            Condition="'$(LiteEdition)' == 'true'"
        />
        <Exec
            Command="npx tsx scripts/post-merge.ts MyCarbonoxide.cs --edition=full"
            Condition="'$(LiteEdition)' == 'true'"
        />
        <Exec
            Command="npx tsx scripts/post-merge.ts lite/MyCarbonoxide.cs --edition=lite"
            Condition="'$(LiteEdition)' == 'true'"
        />

        <!-- Formats the file for consistent outputs and avoid things like spaces and line breaks to appear as diffs -->
        <Exec Command="dotnet tool run csharpier -- format ." />
        <!-- `format .` skips gitignored files, so the merged files are formatted explicitly in case they're ignored -->
        <Exec Command="dotnet tool run csharpier -- format MyCarbonoxide.cs --ignore-path .csharpierignore" />
        <Exec
            Command="dotnet tool run csharpier -- format lite/MyCarbonoxide.cs --ignore-path .csharpierignore"
            Condition="'$(LiteEdition)' == 'true'"
        />
    </Target>
</Project>
